"""Legal build compilation and deterministic quality-diversity search."""

from .build_compiler import LegalBuildCompiler
from .build_io import load_legal_build_genome, load_legal_build_genome_text
from .build_model import (
    LEGAL_BUILD_COMPILER_VERSION,
    LEGAL_BUILD_GENOME_SCHEMA_VERSION,
    BuildCompilationStatus,
    BuildCoverageReport,
    CompiledLegalBuild,
    EquipmentSelection,
    LegalBuildCompileError,
    LegalBuildCompilePolicy,
    LegalBuildGenome,
    SelectedAffix,
)
from .map_elites import (
    ArchiveAdmission,
    DescriptorAxis,
    MapElitesArchive,
    MapElitesCell,
    MapElitesError,
    MapElitesEvaluation,
    MapElitesInsertStatus,
    MapElitesRun,
    run_map_elites,
)
from .training import (
    CatalogBackedLegalityGate,
    CatalogLegalityAudit,
    CompiledOpponent,
    CompilerBackedGenomeMutator,
    DuelScenario,
    EquipmentSkillRequirement,
    LegalBuildLeagueEvaluator,
    evaluation_digest,
    genome_mechanical_digest,
    genome_mechanical_payload,
)

__all__ = [
    "LEGAL_BUILD_COMPILER_VERSION",
    "LEGAL_BUILD_GENOME_SCHEMA_VERSION",
    "ArchiveAdmission",
    "BuildCompilationStatus",
    "BuildCoverageReport",
    "CatalogBackedLegalityGate",
    "CatalogLegalityAudit",
    "CompiledLegalBuild",
    "CompiledOpponent",
    "CompilerBackedGenomeMutator",
    "DescriptorAxis",
    "DuelScenario",
    "EquipmentSelection",
    "EquipmentSkillRequirement",
    "LegalBuildCompileError",
    "LegalBuildCompilePolicy",
    "LegalBuildCompiler",
    "LegalBuildGenome",
    "LegalBuildLeagueEvaluator",
    "MapElitesArchive",
    "MapElitesCell",
    "MapElitesError",
    "MapElitesEvaluation",
    "MapElitesInsertStatus",
    "MapElitesRun",
    "SelectedAffix",
    "evaluation_digest",
    "genome_mechanical_digest",
    "genome_mechanical_payload",
    "load_legal_build_genome",
    "load_legal_build_genome_text",
    "run_map_elites",
]
