"""Local multi-client discovery, lifecycle, and guarded window-management primitives."""

from .manifest import (
    MANAGER_MANIFEST_SCHEMA_VERSION,
    ClientLaunchConfig,
    ManagedClientConfig,
    ManagerManifest,
    ManagerManifestError,
    WindowTile,
    load_manager_manifest,
    loads_manager_manifest,
    parse_manager_manifest,
)
from .model import (
    MANAGER_SNAPSHOT_SCHEMA_VERSION,
    ClientInstanceSnapshot,
    ClientRegistrySnapshot,
    RejectedWindowSnapshot,
    WindowRejectionReason,
)
from .registry import (
    ClientRegistryError,
    ClientWindowRegistry,
    DuplicateClientIdentityError,
    derive_client_instance_id,
)
from .supervisor import (
    AmbiguousClientError,
    ClientInstanceSelector,
    ClientLifecycleSupervisor,
    LaunchTimeoutError,
    ManagedClientSnapshot,
    ManagedClientState,
    NoMatchingClientError,
    ReviewedLaunchCommand,
    StaleManagedClientError,
    SubprocessLauncher,
    SupervisorError,
    VisibleWindowRegistrySource,
    launch_command_from_config,
    selector_from_config,
    window_rectangle_from_config,
)
from .window_control import (
    GuardedWindowControl,
    StaleClientIdentityError,
    Win32WindowApi,
    WindowActionError,
    WindowControlError,
    WindowRectangle,
)

__all__ = [
    "MANAGER_SNAPSHOT_SCHEMA_VERSION",
    "MANAGER_MANIFEST_SCHEMA_VERSION",
    "AmbiguousClientError",
    "ClientInstanceSnapshot",
    "ClientInstanceSelector",
    "ClientLaunchConfig",
    "ClientLifecycleSupervisor",
    "ClientRegistryError",
    "ClientRegistrySnapshot",
    "ClientWindowRegistry",
    "DuplicateClientIdentityError",
    "GuardedWindowControl",
    "LaunchTimeoutError",
    "ManagedClientConfig",
    "ManagedClientSnapshot",
    "ManagedClientState",
    "ManagerManifest",
    "ManagerManifestError",
    "NoMatchingClientError",
    "RejectedWindowSnapshot",
    "ReviewedLaunchCommand",
    "StaleClientIdentityError",
    "StaleManagedClientError",
    "SubprocessLauncher",
    "SupervisorError",
    "VisibleWindowRegistrySource",
    "Win32WindowApi",
    "WindowActionError",
    "WindowControlError",
    "WindowRejectionReason",
    "WindowRectangle",
    "WindowTile",
    "derive_client_instance_id",
    "launch_command_from_config",
    "load_manager_manifest",
    "loads_manager_manifest",
    "parse_manager_manifest",
    "selector_from_config",
    "window_rectangle_from_config",
]
