"""Guarded semantic-decision to desktop-input tooling."""

from shadowbane_lab.client_input.calibration import (
    CalibrationLoadError,
    load_calibration,
    load_calibration_text,
)
from shadowbane_lab.client_input.compiler import (
    BindingPointResolver,
    DecisionInputCompiler,
    InputCompilationError,
    StaticBindingPointResolver,
)
from shadowbane_lab.client_input.model import (
    CLIENT_PROFILE_SCHEMA_VERSION,
    AbsolutePoint,
    ActionInputMapping,
    CalibrationProfile,
    CameraDragMapping,
    ClickActivation,
    ClickCommand,
    ClientTarget,
    DirectionalClickMapping,
    DragCommand,
    HotkeyActivation,
    HotkeyCommand,
    InputCommand,
    InputPlan,
    KeyActivation,
    KeyPressCommand,
    MouseButton,
    NormalizedPoint,
    TargetOrder,
    WaitCommand,
    WindowBounds,
)

__all__ = [
    "CLIENT_PROFILE_SCHEMA_VERSION",
    "AbsolutePoint",
    "ActionInputMapping",
    "BindingPointResolver",
    "CalibrationLoadError",
    "CalibrationProfile",
    "CameraDragMapping",
    "ClickActivation",
    "ClickCommand",
    "ClientTarget",
    "DecisionInputCompiler",
    "DirectionalClickMapping",
    "DragCommand",
    "HotkeyActivation",
    "HotkeyCommand",
    "InputCommand",
    "InputCompilationError",
    "InputPlan",
    "KeyActivation",
    "KeyPressCommand",
    "MouseButton",
    "NormalizedPoint",
    "StaticBindingPointResolver",
    "TargetOrder",
    "WaitCommand",
    "WindowBounds",
    "load_calibration",
    "load_calibration_text",
]
