"""Safe, offline preparation for the persistent WonderBane client extension."""

from .baseline import (
    CLIENT_BASELINE_SCHEMA_VERSION,
    BaselineFile,
    ClientBaseline,
    ClientBaselineError,
    freeze_client_baseline,
)
from .heartbeat import (
    EXTENSION_ABI_VERSION,
    EXTENSION_HEARTBEAT_SCHEMA_VERSION,
    ExtensionHeartbeat,
    ExtensionHeartbeatError,
    load_extension_heartbeat,
    parse_extension_heartbeat,
)
from .manifest import (
    PATCH_MANIFEST_SCHEMA_VERSION,
    ExtensionArtifact,
    MaskedSignature,
    PatchManifest,
    PatchManifestError,
    PatchSite,
    SourceExecutable,
    load_patch_manifest,
)
from .package import (
    PATCH_PACKAGE_SCHEMA_VERSION,
    ROLLBACK_RECEIPT_SCHEMA_VERSION,
    ClientPatchPackageError,
    PatchPackageEvidence,
    PatchPackageResult,
    RollbackReceipt,
    VerifiedClientBaseline,
    discard_patched_client_copy,
    prepare_patched_client_copy,
    verify_frozen_client_baseline,
    verify_patched_client_copy,
)
from .resolver import (
    PatchAlignmentReport,
    PatchPlan,
    PatchResolutionError,
    PatchSiteResolution,
    PatchSiteStatus,
    PatchWrite,
    align_patch_sites,
    apply_patch_plan,
    build_patch_plan,
)

__all__ = [
    "CLIENT_BASELINE_SCHEMA_VERSION",
    "EXTENSION_ABI_VERSION",
    "EXTENSION_HEARTBEAT_SCHEMA_VERSION",
    "PATCH_MANIFEST_SCHEMA_VERSION",
    "PATCH_PACKAGE_SCHEMA_VERSION",
    "ROLLBACK_RECEIPT_SCHEMA_VERSION",
    "BaselineFile",
    "ClientBaseline",
    "ClientBaselineError",
    "ClientPatchPackageError",
    "ExtensionArtifact",
    "ExtensionHeartbeat",
    "ExtensionHeartbeatError",
    "MaskedSignature",
    "PatchAlignmentReport",
    "PatchManifest",
    "PatchManifestError",
    "PatchPackageEvidence",
    "PatchPackageResult",
    "PatchPlan",
    "PatchResolutionError",
    "PatchSite",
    "PatchSiteResolution",
    "PatchSiteStatus",
    "PatchWrite",
    "RollbackReceipt",
    "SourceExecutable",
    "VerifiedClientBaseline",
    "align_patch_sites",
    "apply_patch_plan",
    "build_patch_plan",
    "discard_patched_client_copy",
    "freeze_client_baseline",
    "load_patch_manifest",
    "load_extension_heartbeat",
    "parse_extension_heartbeat",
    "prepare_patched_client_copy",
    "verify_frozen_client_baseline",
    "verify_patched_client_copy",
]
