"""Scenario rollouts and deterministic baseline policies."""

from shadowbane_lab.rollouts.duel import (
    ActionCount,
    CombatantConfig,
    CombatantResult,
    DuelConfig,
    DuelResult,
    ProgressionMatrixCell,
    TerminationReason,
    UtilityDuelPolicy,
    matched_progression_duels,
    progression_build,
    progression_duel_matrix,
    run_duel,
)
from shadowbane_lab.rollouts.open_builds import (
    OpenBuildError,
    OpenDuelRun,
    OpenMatchupCell,
    PrimitiveLoadout,
    ResolvedPrimitiveLoadout,
    generate_primitive_loadouts,
    load_open_roster,
    load_open_roster_text,
    resolve_primitive_loadout,
    round_robin_open_duels,
    run_open_duel,
)
from shadowbane_lab.rollouts.presets import (
    CombatantPreset,
    wonderbane_deflock,
    wonderbane_sundancer_proc_assassin,
    wonderbane_sundancer_vs_deflock,
)
from shadowbane_lab.rollouts.ruleset import (
    load_assassin_warlock_duel_ruleset,
    progression_milestones,
)

__all__ = [
    "ActionCount",
    "CombatantConfig",
    "CombatantPreset",
    "CombatantResult",
    "DuelConfig",
    "DuelResult",
    "OpenBuildError",
    "OpenDuelRun",
    "OpenMatchupCell",
    "PrimitiveLoadout",
    "ProgressionMatrixCell",
    "ResolvedPrimitiveLoadout",
    "TerminationReason",
    "UtilityDuelPolicy",
    "generate_primitive_loadouts",
    "load_assassin_warlock_duel_ruleset",
    "load_open_roster",
    "load_open_roster_text",
    "matched_progression_duels",
    "progression_build",
    "progression_duel_matrix",
    "progression_milestones",
    "resolve_primitive_loadout",
    "round_robin_open_duels",
    "run_duel",
    "run_open_duel",
    "wonderbane_deflock",
    "wonderbane_sundancer_proc_assassin",
    "wonderbane_sundancer_vs_deflock",
]
