"""Structured, read-only access to Shadowbane world assets."""

from shadowbane_lab.world_data.cache import (
    CacheArchive,
    CacheArchiveFormatError,
    CacheArchiveHeader,
    CacheResourceEntry,
)
from shadowbane_lab.world_data.object_navigation import (
    MeshNavigationBounds,
    ObjectCollisionProfile,
    ObjectNavigationFormatError,
    ObjectNavigationMetadata,
    ObjectNavigationResolver,
    RenderNavigationMetadata,
    parse_mesh_navigation_bounds,
    parse_object_navigation_metadata,
    parse_render_navigation_metadata,
)
from shadowbane_lab.world_data.terrain import (
    TerrainAlphaFormatError,
    TerrainAlphaMap,
    TerrainAlphaRaster,
    TerrainAlphaTile,
    TerrainTileAddress,
    index_terrain_alpha_maps,
    read_terrain_alpha_map,
)
from shadowbane_lab.world_data.world import (
    WorldDefinition,
    WorldDefinitionFormatError,
    ZonePlacement,
    load_world_definition,
    parse_world_definition,
)
from shadowbane_lab.world_data.zone import (
    ZoneTerrainCorrelation,
    ZoneTerrainCorrelationError,
    ZoneTerrainMapReference,
    correlate_zone_terrain,
)
from shadowbane_lab.world_data.zone_metadata import (
    ZoneMetadataFormatError,
    ZoneNavigationMetadata,
    ZoneResourceKey,
    ZoneSeaLevelType,
    ZoneTerrainGeneration,
    ZoneTerrainObjectPopulation,
    ZoneWaterMetadata,
    parse_zone_navigation_metadata,
)

__all__ = [
    "CacheArchive",
    "CacheArchiveFormatError",
    "CacheArchiveHeader",
    "CacheResourceEntry",
    "MeshNavigationBounds",
    "ObjectCollisionProfile",
    "ObjectNavigationFormatError",
    "ObjectNavigationMetadata",
    "ObjectNavigationResolver",
    "RenderNavigationMetadata",
    "TerrainAlphaFormatError",
    "TerrainAlphaMap",
    "TerrainAlphaRaster",
    "TerrainAlphaTile",
    "TerrainTileAddress",
    "WorldDefinition",
    "WorldDefinitionFormatError",
    "ZonePlacement",
    "ZoneTerrainCorrelation",
    "ZoneTerrainCorrelationError",
    "ZoneTerrainMapReference",
    "ZoneMetadataFormatError",
    "ZoneNavigationMetadata",
    "ZoneResourceKey",
    "ZoneSeaLevelType",
    "ZoneTerrainGeneration",
    "ZoneTerrainObjectPopulation",
    "ZoneWaterMetadata",
    "correlate_zone_terrain",
    "index_terrain_alpha_maps",
    "read_terrain_alpha_map",
    "load_world_definition",
    "parse_mesh_navigation_bounds",
    "parse_object_navigation_metadata",
    "parse_render_navigation_metadata",
    "parse_world_definition",
    "parse_zone_navigation_metadata",
]
