"""Deterministic reference simulation primitives."""

from shadowbane_lab.sim.actions import (
    ActionCatalog,
    ActionPhase,
    ActionSpec,
    ApplyEffect,
    AreaEffect,
    AreaOrigin,
    AttackGate,
    AttackKind,
    ChanceGate,
    ChangeStance,
    CombatStance,
    DealDamage,
    DeliveryKind,
    DeliverySpec,
    DirectEffectPrimitive,
    EffectPrimitive,
    ModifyObjective,
    ModifyScalar,
    ModifyTag,
    MoveEntity,
    MovementMode,
    PhaseKind,
    RemoveEffect,
    ResourceCost,
    RestoreResource,
    ScalarOperation,
    SubjectRef,
    TagOperation,
    TargetingSpec,
    TransferItem,
    TriangularAmount,
    UniformAmount,
    UniformIntegerAmount,
    WeightedAmount,
)
from shadowbane_lab.sim.clock import ClockSnapshot, SimulationClock
from shadowbane_lab.sim.environment import ReferenceEnvironment
from shadowbane_lab.sim.errors import SimulationConfigurationError
from shadowbane_lab.sim.random_source import (
    DeterministicRandom,
    RandomSnapshot,
)
from shadowbane_lab.sim.range_intent import (
    CLOSE_RANGE_ACTION_KEY,
    RANGE_MAXIMUM_FEATURE,
    RangeBand,
    RangeRelation,
    close_range_action,
)
from shadowbane_lab.sim.state import (
    ActiveEffectSnapshot,
    ActiveEffectState,
    EntitySnapshot,
    EntityState,
)
from shadowbane_lab.sim.timeline import (
    AgentExchange,
    EnvironmentSnapshot,
    ScheduledItem,
    ScheduledKind,
)

__all__ = [
    "ActionCatalog",
    "ActionPhase",
    "ActionSpec",
    "AgentExchange",
    "ApplyEffect",
    "AreaEffect",
    "AreaOrigin",
    "AttackGate",
    "AttackKind",
    "ChanceGate",
    "ChangeStance",
    "CombatStance",
    "ActiveEffectSnapshot",
    "ActiveEffectState",
    "ClockSnapshot",
    "CLOSE_RANGE_ACTION_KEY",
    "DealDamage",
    "DeliveryKind",
    "DeliverySpec",
    "DeterministicRandom",
    "EffectPrimitive",
    "DirectEffectPrimitive",
    "EntitySnapshot",
    "EntityState",
    "EnvironmentSnapshot",
    "ModifyObjective",
    "ModifyScalar",
    "ModifyTag",
    "MoveEntity",
    "MovementMode",
    "PhaseKind",
    "RandomSnapshot",
    "RANGE_MAXIMUM_FEATURE",
    "RangeBand",
    "RangeRelation",
    "ReferenceEnvironment",
    "RemoveEffect",
    "ResourceCost",
    "RestoreResource",
    "ScalarOperation",
    "SimulationClock",
    "ScheduledItem",
    "ScheduledKind",
    "SimulationConfigurationError",
    "SubjectRef",
    "TagOperation",
    "TargetingSpec",
    "TransferItem",
    "TriangularAmount",
    "UniformAmount",
    "UniformIntegerAmount",
    "WeightedAmount",
    "close_range_action",
]
