"""Research cases, bounded experiments, capture, alignment, and execution."""

from .codec import (
    load_case,
    load_experiment,
    parse_case,
    parse_experiment,
    save_case,
    save_experiment,
)
from .model import (
    CapturePolicy,
    CaseError,
    CaseState,
    ExpandedRun,
    ExperimentDefinition,
    ExperimentReference,
    ExperimentStep,
    ExperimentVariable,
    Hypothesis,
    OracleRule,
    OracleSeverity,
    RepetitionPolicy,
    ResearchCase,
    SafetyPolicy,
    StepKind,
    VariableOrder,
    expand_experiment,
    review_case,
)
from .runner import (
    DryRunExecutor,
    RecordedExecutor,
    RunExecution,
    StepOutcome,
    execute_plan,
    execute_run,
    validate_case_experiment,
)

__all__ = [
    "CapturePolicy",
    "CaseError",
    "CaseState",
    "DryRunExecutor",
    "ExpandedRun",
    "ExperimentDefinition",
    "ExperimentReference",
    "ExperimentStep",
    "ExperimentVariable",
    "Hypothesis",
    "OracleRule",
    "OracleSeverity",
    "RecordedExecutor",
    "RepetitionPolicy",
    "ResearchCase",
    "RunExecution",
    "SafetyPolicy",
    "StepKind",
    "StepOutcome",
    "VariableOrder",
    "execute_plan",
    "execute_run",
    "expand_experiment",
    "load_case",
    "load_experiment",
    "parse_case",
    "parse_experiment",
    "review_case",
    "save_case",
    "save_experiment",
    "validate_case_experiment",
]
