"""Sourced character progression and build-effectiveness evaluation."""

from shadowbane_lab.progression.advisor import (
    PowerTarget,
    ProcAssassinRoadmap,
    ProcAssassinTrainingAudit,
    ProcBuildCandidate,
    RankTargetAudit,
    audit_proc_assassin_training,
    irekei_proc_assassin_roadmap,
)
from shadowbane_lab.progression.calculator import (
    IllegalProgressionError,
    ability_points_for_level,
    estimate_procs,
    evaluate_progression,
    focus_skill_cap,
    melee_attack_rating,
    rogue_training_points_for_level,
    spell_damage_range,
)
from shadowbane_lab.progression.loader import (
    ProgressionProfileLoadError,
    load_wonderbane_irekei_proc_profile,
)
from shadowbane_lab.progression.model import (
    CharacterProgression,
    IdentityProfile,
    ProcEffectProfile,
    ProcEstimate,
    ProcLoadout,
    ProgressionEvaluation,
    ProgressionLimits,
    ProgressionProfile,
    RuneKind,
    RuneProfile,
    SourceReference,
    StatLine,
    TrainingInvestment,
    TrainingTarget,
    WeaponProfile,
)

__all__ = [
    "CharacterProgression",
    "IdentityProfile",
    "IllegalProgressionError",
    "PowerTarget",
    "ProcAssassinRoadmap",
    "ProcAssassinTrainingAudit",
    "ProcBuildCandidate",
    "ProcEffectProfile",
    "ProcEstimate",
    "ProcLoadout",
    "ProgressionEvaluation",
    "ProgressionLimits",
    "ProgressionProfile",
    "ProgressionProfileLoadError",
    "RuneKind",
    "RankTargetAudit",
    "RuneProfile",
    "SourceReference",
    "StatLine",
    "TrainingInvestment",
    "TrainingTarget",
    "WeaponProfile",
    "ability_points_for_level",
    "audit_proc_assassin_training",
    "estimate_procs",
    "evaluate_progression",
    "focus_skill_cap",
    "irekei_proc_assassin_roadmap",
    "load_wonderbane_irekei_proc_profile",
    "melee_attack_rating",
    "rogue_training_points_for_level",
    "spell_damage_range",
]
